from pecab._utils._consts import Pos

UNK = {
    "DEFAULT": {
        "surface": "DEFAULT",
        "left_id": 1801,
        "right_id": 3566,
        "word_cost": 3640,
        "POS": "SY",
        "POS_type": Pos.MORPHEME,
        "morphemes": None,
    },
    "SPACE": {
        "surface": "SPACE",
        "left_id": 1798,
        "right_id": 3563,
        "word_cost": 996,
        "POS": "SP",
        "POS_type": Pos.MORPHEME,
        "morphemes": None,
    },
    "ALPHA": {
        "surface": "ALPHA",
        "left_id": 1796,
        "right_id": 3532,
        "word_cost": 824,
        "POS": "SL",
        "POS_type": Pos.MORPHEME,
        "morphemes": None,
    },
    "CYRILLIC": {
        "surface": "CYRILLIC",
        "left_id": 1796,
        "right_id": 3532,
        "word_cost": 824,
        "POS": "SL",
        "POS_type": Pos.MORPHEME,
        "morphemes": None,
    },
    "GREEK": {
        "surface": "GREEK",
        "left_id": 1796,
        "right_id": 3532,
        "word_cost": 824,
        "POS": "SL",
        "POS_type": Pos.MORPHEME,
        "morphemes": None,
    },
    "HANGUL": {
        "surface": "HANGUL",
        "left_id": 1803,
        "right_id": 3569,
        "word_cost": 10055,
        "POS": "UNKNOWN",
        "POS_type": Pos.MORPHEME,
        "morphemes": None,
    },
    "HANJA": {
        "surface": "HANJA",
        "left_id": 1795,
        "right_id": 3561,
        "word_cost": -803,
        "POS": "SH",
        "POS_type": Pos.MORPHEME,
        "morphemes": None,
    },
    "HIRAGANA": {
        "surface": "HIRAGANA",
        "left_id": 1796,
        "right_id": 3532,
        "word_cost": 824,
        "POS": "SL",
        "POS_type": Pos.MORPHEME,
        "morphemes": None,
    },
    "KANJI": {
        "surface": "KANJI",
        "left_id": 1796,
        "right_id": 3532,
        "word_cost": 824,
        "POS": "SL",
        "POS_type": Pos.MORPHEME,
        "morphemes": None,
    },
    "HANJANUMERIC": {
        "surface": "HANJANUMERIC",
        "left_id": 1795,
        "right_id": 3561,
        "word_cost": -803,
        "POS": "SH",
        "POS_type": Pos.MORPHEME,
        "morphemes": None,
    },
    "KATAKANA": {
        "surface": "KATAKANA",
        "left_id": 1796,
        "right_id": 3532,
        "word_cost": 824,
        "POS": "SL",
        "POS_type": Pos.MORPHEME,
        "morphemes": None,
    },
    "NUMERIC": {
        "surface": "NUMERIC",
        "left_id": 1797,
        "right_id": 3562,
        "word_cost": 3563,
        "POS": "SN",
        "POS_type": Pos.MORPHEME,
        "morphemes": None,
    },
    "SYMBOL": {
        "surface": "SYMBOL",
        "left_id": 1801,
        "right_id": 3566,
        "word_cost": 3640,
        "POS": "SY",
        "POS_type": Pos.MORPHEME,
        "morphemes": None,
    },
    "EMOJI": {
        "surface": "EMOJI",
        "left_id": 1801,
        "right_id": 3566,
        "word_cost": 3640,
        "POS": "SY",
        "POS_type": Pos.MORPHEME,
        "morphemes": None,
    },
}
